apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: gitea-charts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gitea
    app.kubernetes.io/version: 1.12.3
    helm.sh/chart: gitea-1.4.1
  name: gitea-charts
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea-charts
      app.kubernetes.io/name: gitea
  serviceName: gitea-charts
  template:
    metadata:
      annotations:
        checksum/config: b0f997e73a07b46281fd3ec4fccf9333b1c586543a862686106f734d4fea0260
      labels:
        app.kubernetes.io/instance: gitea-charts
        app.kubernetes.io/name: gitea
    spec:
      containers:
      - env:
        - name: SSH_LISTEN_PORT
          value: "22"
        - name: SSH_PORT
          value: "22"
        image: gitea/gitea:1.12.3
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 200
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
          timeoutSeconds: 1
        name: gitea
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: http
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: data
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |-
          mkdir -p /data/gitea/conf
          cp /etc/gitea/conf/app.ini /data/gitea/conf/app.ini
          chmod a+rwx /data/gitea/conf/app.ini
          nc -v -w2 -z gitea-charts-postgresql 5432 && \
          su git -c ' \
          set -x; \
          gitea migrate; \
          gitea admin create-user --username gitea_admin --password $(GITEA_ADMIN_PASSWORD) --email gitea@local.domain --admin \
          || \
          gitea admin change-password --username gitea_admin --password $(GITEA_ADMIN_PASSWORD); \
          '
        env:
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-admin-secret
              key: password
        - name: SCRIPT
          value: |-
            mkdir -p /data/gitea/conf
            cp /etc/gitea/conf/app.ini /data/gitea/conf/app.ini
            chmod a+rwx /data/gitea/conf/app.ini
            nc -v -w2 -z gitea-charts-postgresql 5432 && \
            su git -c ' \
            set -x; \
            gitea migrate; \
            gitea admin create-user --username gitea_admin --password $(GITEA_ADMIN_PASSWORD) --email gitea@local.domain --admin \
            || \
            gitea admin change-password --username gitea_admin --password $(GITEA_ADMIN_PASSWORD); \
            '
        image: gitea/gitea:1.12.3
        name: init
        volumeMounts:
        - mountPath: /etc/gitea/conf
          name: config
        - mountPath: /data
          name: data
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          name: gitea-charts
        name: config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard