apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
spec:
  storageClassName: homeassistant-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
