apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: platform
spec:
  revisionHistoryLimit: 4
  project: default
  source:
    repoURL: git@github.com:brendanPro/homelab.git
    targetRevision: main
    path: apps/infra/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
