apiVersion: v1
kind: Service
metadata:
  name: immich-postgres-pg16
  labels:
    app.kubernetes.io/component: postgres-pg16
spec:
  selector:
    app.kubernetes.io/component: postgres-pg16
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
