kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data
spec:
  storageClassName: mosquitto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-log
spec:
  storageClassName: mosquitto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
