apiVersion: ENC[AES256_GCM,data:Q1g=,iv:/LZmHpcJWt2Xe9XEZR3FvDZxnvypk/HmVnB86f/sYps=,tag:jqdhyS5dWFw0A6z51JHcSA==,type:str]
kind: ENC[AES256_GCM,data:ZLe9c1Hw,iv:Uo/nOoXJ6bbmo88w5g3I4zAzpPlZhCGGP9WpIevOi5M=,tag:kHT1OST0SmLrAziU3maj8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GTVafJ2opEaOvh6w,iv:2BNvoYgvtNqeT9u4perP7weXnjNllfCExz6SdrWDyAQ=,tag:0RRDZAs/z09sQOrxonF36w==,type:str]
    namespace: ENC[AES256_GCM,data:BMQdAJY=,iv:Lo2u3YIYW5WEyINbpZbgqH8alGW3YR0qt7G0XRqxohY=,tag:ZEMU20+B0HtX6+3STJKoKg==,type:str]
type: ENC[AES256_GCM,data:D7Pxo1pH,iv:SAzXu1FZnykviUdVpIDMXRZa4v4lgtOb4t647kuwv1c=,tag:JddJfc9NNv5jvo2hwvbRGw==,type:str]
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:4n4cj7B7vjqD79IpRdevcCca3Rc8v2vXBLrQuqhokBCW3aT95lioJJ3bQdeZttlzezDgxHsXbhfO8qHLFc3mJ7oZrmt04/v8mJ0OSx5KCA3AGT/FzfG8ayJqtSMVdYZr4UejMqRPD2Z7Q3xkb8qkohu/sHWihROLzUsgvwqJE1WxyDYc57KAB5JNnQMWtUZHAKWGRf+Oiw==,iv:sj0Uqp5GCxp/G2j7094waKKl2v1yJWJyE9HCBQ92hNE=,tag:NZjhJkVYVckAqMOIIKgPfQ==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:5Vc23GSKAcPZW4cfjK3+V7pJpOEI8K1RQf0vG02PprghIAChn8zeb2mIQG6n+nLT9wEHQ46VXC93xLM498BZ2g==,iv:nqmVehmis33Tr3aZURoj8fs0aGEFAqV0CqJ3GhgHbC8=,tag:ygQMz61Lc2crk+kk+zoQuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcGlwNGNqT0dxdEw3RE1Y
            YVFXN3htWjVvSFpvRWFoNVBYdWZRdHNabERBCm1JRTZSWEhEemtndVpuQnR3MjBZ
            eS9GQjRubEJuVDI4NGgwWVBab3FDVXcKLS0tIEV3QTdpUGpIZXY2TmlBUmFlL1FP
            RTFrTzFMcnZpQTZOZnU2QVdSb0IwSk0Kyd5AtApM/oCRIN6JSbMRYNSsyH3FVavt
            XUCvmAg/Fn628eNjI+aJg2ZWL0b1TWTO+9pgWGRlcNQgu5xUyUcJjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-08-01T18:39:52Z"
    mac: ENC[AES256_GCM,data:XzFH+W6b7pBzHi7YiWDgAp6QhNh9tPhd0hr2NPMXbNAmcDBASX1kf0yko5iDX/RfSIAy8VXeVi1D2DfxQXS2nWgHZaLLUkQUzaBU/JuPIW4XY7PRPhf9Y63AQoROS0f8iQTSSfqNsngTwBZI5tsMJZKCKOd9W3gT/sokRvQBdC4=,iv:MQeDBiOmiz4+kTHSzbg+wz8/taHbkV7kNlU2Q94wOlU=,tag:CquXCPnFQnW5+7HUO+KlPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
