apiVersion: ENC[AES256_GCM,data:6N4=,iv:86CickWYyMFt0Knm8Weof+Ij2qXGSnAmrapu/UnHbW0=,tag:t1Z5CmWmSXFJgMOGYWXzjg==,type:str]
kind: ENC[AES256_GCM,data:LtcMxXo3,iv:jFsJbaVvd21gHz/eyaxsVfxushJSboMf8OI3A1OX4VM=,tag:VVlIZ23SCzCVcfypj/dDQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YsU1QDDp6yjO6Zt1SJ8h,iv:fqXgYQCiGOEZZuLXevVoydpaQ3VnssbqsTGdZK9N7RM=,tag:rnrCBNUcnl+GmauPS5SXMw==,type:str]
    namespace: ENC[AES256_GCM,data:PYkAfaZ5CkM=,iv:GEo33ZyYS6r/E4Py15TnrVxu2tUBQPEH4AeGOiwFbQ8=,tag:/zJVDxe5CuzIBRkBZocW9A==,type:str]
type: ENC[AES256_GCM,data:JiHR7ucL,iv:nBp9Br5sDSgP5yxtzNWfv6gISWYOK/QYImlnOdwgCKA=,tag:r+5Wk8nLkATtZpfAmjrXUQ==,type:str]
stringData:
    USERNAME: ENC[AES256_GCM,data:KOazR3hN3Dn/,iv:LTgvw2emLf9eqWgufVMT9vGzK/+4D5h9x6ZbVxpNMNA=,tag:BpXjg8Mn/7ncn3o+ezVi5A==,type:str]
    TOKEN: ENC[AES256_GCM,data:YqZej9GwXR1Z1bFf92mAiVlZsReesRVgJ1khXv6K,iv:T81MJObDcUJ/ISgv+9Qo1nIBcYBWboVh0bYtsPIke40=,tag:udt9MfvBunSYgxkkioZTcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS0dqUDRqOCtzTkZaM3VT
            cUoyV0VOZ0hJSVgvOFZiMkowME9HczlpNWtvCnVLRm9CUVhIZ1BpQTVFUG5qYnht
            Z3hCNzV5TDk0SzVhOVN4eDVkVDA4T2cKLS0tIEtKZTROQ2JMWTdZYktuSkNOWmVv
            bGcvNFVHcytnRjRhRFV1K2NWK3pIOFUKHJmUGwvqX5Tp9H4UDLZ5iGK6CX8kjyV2
            QFQ6V3ZFA84lmUYRuvcI/ElXl8SD2Ua/UjOwZNGHnrxvDoOWU4M6iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-07-18T09:10:24Z"
    mac: ENC[AES256_GCM,data:VPziusM2FZB44K7t5LoMa207jffS7Wqo4tq8WlS7OyKtKCPAwJUfMfR+yMd9HXm1du2y4WHS0Bb07+tg4miYaPKvJxbcRBym0LAULLJ+4m1BBUvDAepUjbPE72D0wK1AXCQh4e8sDEraYYTXEsw68+7lnrdDVn960HgIf8T7fYw=,iv:ks96wthgNTy8LQrmGUGbp3FbYnbJ2RY7NqEng2Au3LQ=,tag:e4jnr8LDB3V29O1wQFKE1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
