apiVersion: v1
kind: Service
metadata:
  name:  factorio
spec:
  type: LoadBalancer 
  loadBalancerClass: tailscale
  ports:
  - name: factorio-udp
    port: 34197
    targetPort: 34197
    protocol: UDP
