apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  storageClassName: prowlarr-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
