namespace: kube-system

labels:
- pairs:
    app.kubernetes.io/name: metrics-server
  includeSelectors: false

resources:
- ./resources.yaml

images:
- name: registry.k8s.io/metrics-server/metrics-server
  newTag: v0.7.1
