apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw-operator
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  revisionHistoryLimit: 4
  project: default
  source:
    repoURL: https://github.com/openclaw-rocks/k8s-operator.git
    targetRevision: v0.10.16
    path: config/default
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
