apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
spec:
  storageClassName: jellyseerr-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
