apiVersion: ENC[AES256_GCM,data:EKg=,iv:AL1SiTh0TjxHhjyu9UqrnJnzg73XuBoWgPlrzmFcpe8=,tag:93Z9GiMtls+wGnv+lfEUNg==,type:str]
kind: ENC[AES256_GCM,data:+ASiRs92,iv:fBwbcEfH/R2wULsiK/068hufMWclelTxaT53dAP2TTU=,tag:r4PPQdnDh1hAErVGdLOjyg==,type:str]
type: ENC[AES256_GCM,data:IvWn72Q7h2+oTdI/PFU8+Rp8ld5lbBKoyso0ExgGNNfXdeo=,iv:HTlgpkZWWr3cYHNM1KoXg9k37MJmzTnP2zxpWO7JjoQ=,tag:fZ9Nf45s/dKTPpiU2cCLBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:U+BxrMXOiEA=,iv:sOvXLarPP+rhb1crCXl/72I1rkva1SKx0ynffVAFUQg=,tag:v0tmgON1Qr0XBSaFYlAr1Q==,type:str]
    namespace: ENC[AES256_GCM,data:ezPkOamNXV/2pw==,iv:TmG9FrHGMTlIUn/KtvhPj5DM1rd5Yzw/gnzbh2DNg1A=,tag:frnUNvaXIbaa/6KFQtWJXA==,type:str]
    annotations:
        kubernetes.io/service-account.name: ENC[AES256_GCM,data:dBOAPMGSwPQ=,iv:nQZPIQchj86occ6nsPSy4uVoec4JqJXkxkAk32y0OMQ=,tag:XOPjzojEjywNrHgB+gCBaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ODBROGtXalh0R0NES0p6
            RXRHSnBLMSt4RTFraEFqeFNWZVpGN0E1ZEJRCjIzaXR2RW5WNEFDOHY2dmwyQmV5
            bUhsRTIzclJIcUgrNmZjbEJjRm9IM2sKLS0tIGQ0ckUzRi9BRFpONGlLSUd4Skhz
            MmlJc0xwdk9zRXgyYTJwdll4Y01qVUUKJMKKgPE8KqSF+bpSkNCZ3mu2of5c5WAB
            pU/BJq3PiAxMkXZRE9ZMlffKDu+sJ9GDUHuYspP9i3RrMoKXT5CwAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-07-18T10:27:28Z"
    mac: ENC[AES256_GCM,data:mHjx/fNOrk9ZbdDiRmiYB5HhXwUjCwBOxbYkTKSXc69kYlYBUhDyHdQyUVOUkHnqnx82nHBx0JzsbQwzBscoA9YnFEsnNGvkjLWjIFBEmTEd1WnQCy4n6oRaUBIr/0QkVuH/LS/6+WOnoEKYjSG82Q3mIkaColPALHRfGYfgOJ8=,iv:dQmt2yjCljxYt2A2L1KvYdmoD0OrbbVhlWQcmMaQcts=,tag:pmg5tkYqsen5q9SOFykSxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
