apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-config
  namespace: vaultwarden
data:
  ADMIN_RATELIMIT_MAX_BURST: "3"
  ADMIN_RATELIMIT_SECONDS: "300"
  DATABASE_MAX_CONNS: "10"
  DB_CONNECTION_RETRIES: "15"
  DOMAIN: "https://newvaultwarden.wombat-wahoo.ts.net"
  EMAIL_CHANGE_ALLOWED: "true"
  EMERGENCY_ACCESS_ALLOWED: "true"
  EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE: "0 3 * * * *"
  EMERGENCY_REQUEST_TIMEOUT_SCHEDULE: "0 7 * * * *"
  EXTENDED_LOGGING: "true"
  ICON_BLACKLIST_NON_GLOBAL_IPS: "true"
  ICON_REDIRECT_CODE: "302"
  ICON_SERVICE: "internal"
  INVITATION_EXPIRATION_HOURS: "120"
  INVITATION_ORG_NAME: "Vaultwarden"
  INVITATIONS_ALLOWED: "true"
  IP_HEADER: "X-Real-IP"
  LOG_TIMESTAMP_FORMAT: "'%Y-%m-%d %H=%M=%S.%3f' "
  ORG_EVENTS_ENABLED: "false"
  ORG_GROUPS_ENABLED: "false"
  REQUIRE_DEVICE_EMAIL: "false"
  SENDS_ALLOWED: "true"
  SHOW_PASSWORD_HINT: "false"
  SIGNUPS_ALLOWED: "false"
  SIGNUPS_VERIFY: "true"
