apiVersion: ENC[AES256_GCM,data:XFM=,iv:bPBK8lelIV7O2R9CZp1jGn28YeRzpppShDtYtaoiags=,tag:8bP32dJCB5bjmooScXpCjg==,type:str]
kind: ENC[AES256_GCM,data:zT2a4t5T,iv:Hbs1nyYq4xO4fXmBecCLKKr7GVxcUH1ZAUPFJXOWImw=,tag:tJ2fHuSBX/Om2Z+KTimt8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:f5ESS5Rq9R/zhegBOsj/wzmN,iv:jpDS7jtTZdfZzY86XurDaBCHN6rrVaM8QPpgoagrA1U=,tag:bAYyNrXjKOFfbfpjgaoRsg==,type:str]
    namespace: ENC[AES256_GCM,data:Sd3VjO7guiACkMA=,iv:x0qS6VL13UkxUHtAQsKWX3iL9jV+aFiQRBr0gCeqUB0=,tag:AEPhG3PyAKkpnfnP5DKzcw==,type:str]
type: ENC[AES256_GCM,data:9L7ON1JN,iv:Jfg7S4lSiAavfYlBIUb3uDv3+gXLaC2MmWoryMXsR4o=,tag:VM49ncB7T1XFhEpc+3Vz2Q==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:RIx8ewfJo5c3zMWHTpbnxks0DzBLqBe0srBBvSq+BO0vpjdDGLm+GoQLAA14haVz9r0LXogWBLCjdIB9DbmG,iv:8pjwCeHyza8Z7p/gyS5kZUDS7lpwwDVf6mXBe4boaKk=,tag:L0XO2CkXmgTRMXB5DOTY6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaTlFTmRCZW9acVhVVlpO
            THh3N2JzbEhUVU1DZUJybDh0NzNJQ1pqWkdJCmsxT3VqVzFGd3RWUHZPS25hRVEw
            czRXU1hxU0F3L1NHb2xmb0FudGZuNlkKLS0tIFdBYmtYeDFtMFhTRFNTZmljc3hr
            QzBrWmR1VStYdXFGZ0xJMzJYdUEvQWsKFtlDi6T9xVTqw+65oaeUTy1+undTeKvz
            ICgMZUYIqHzGDAzdrt51xzvX2y/gi3pTg4hqgM6v9QacLZh/s1tkVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-07-18T09:10:24Z"
    mac: ENC[AES256_GCM,data:HkfPir9te/U2vT5IfAEzXCstoAY9w4o4+O143z2Y/9b0odsnbNVmo1qy5boioiJg7FfXzJO576KyvIo94NupIoYcOVo0muCZb65aXjhJP+ut7i6mvUj3kZEuzf7bHsSVYXqu3DufNYTDzq1BXSQOGCpnk4lhDLQJ6Wj8cu+OJOY=,iv:E26LNb7CPRaOnZYA2ByI1TkLUODwj/2L13eXa3Lw/mg=,tag:0tq9GCOIZ9cMM9E3GG4oCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
