apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  storageClassName: jellyfin-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
