apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    app.kubernetes.io/name: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
    spec:
      serviceAccountName: velero
      restartPolicy: Always
      containers:
      - name: velero
        image: velero/velero:v1.13.0
        imagePullPolicy: IfNotPresent
        command:
        - /velero
        args:
        - server
        - --features=
        - --uploader-type=restic
        volumeMounts:
        - name: plugins
          mountPath: /plugins
        - name: scratch
          mountPath: /scratch
        env:
        - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LD_LIBRARY_PATH
          value: /plugins
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      initContainers:
      - name: velero-plugin-for-csi
        image: velero/velero-plugin-for-csi:v0.7.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /target
          name: plugins
      volumes:
      - name: plugins
        emptyDir: {}
      - name: scratch
        emptyDir: {}

