apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openclaw
subjects:
  - kind: ServiceAccount
    name: openclaw
    namespace: ai
roleRef:
  kind: ClusterRole
  name: openclaw
  apiGroup: rbac.authorization.k8s.io
