apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: ai
spec:
  env:
    - name: GOOGLE_GENERATIVE_AI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openclaw-llm-keys
          key: GEMINI_API_KEY
  config:
    raw:
      gateway:
        controlUi:
          allowedOrigins:
            - "https://openclaw.wombat-wahoo.ts.net"
      models:
        providers:
          google:
            api: "google-generative-ai"
            baseUrl: "https://generativelanguage.googleapis.com/v1beta"
            apiKey: "GOOGLE_GENERATIVE_AI_API_KEY"
            models:
              - id: "gemini-2.0-flash"
                name: "Gemini 2.0 Flash"
                input: ["text", "image"]
                cost: {input: 0, output: 0, cacheRead: 0, cacheWrite: 0}
                contextWindow: 1048576
                maxTokens: 8192
              - id: "gemini-1.5-flash"
                name: "Gemini 1.5 Flash"
                input: ["text", "image"]
                cost: {input: 0, output: 0, cacheRead: 0, cacheWrite: 0}
                contextWindow: 1048576
                maxTokens: 8192
      agents:
        defaults:
          model:
            primary: "google/gemini-2.0-flash"
  storage:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openclaw
  networking:
    networkPolicy:
      enabled: false
    ingress:
      enabled: false
