apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: ai
spec:
  env:
    - name: GEMINI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openclaw-llm-keys
          key: GEMINI_API_KEY
  config:
    raw:
      gateway:
        controlUi:
          allowedOrigins:
            - "https://openclaw.wombat-wahoo.ts.net"
      agents:
        defaults:
          model:
            primary: "google/gemini-flash-latest"
  storage:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openclaw
  networking:
    networkPolicy:
      enabled: false
    ingress:
      enabled: false
