apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: ai
spec:
  env:
    - name: OLLAMA_HOST
      value: "http://ollama.ai.svc.cluster.local:11434"
    - name: OLLAMA_API_KEY
      value: "ollama-local"
  config:
    raw:
      gateway:
        controlUi:
          allowedOrigins:
            - "https://openclaw.wombat-wahoo.ts.net"
      models:
        providers:
          ollama:
            baseUrl: "http://ollama.ai.svc.cluster.local:11434"
            api: "ollama"
            models:
              - id: "llama3.2:1b"
                name: "Llama 3.2 1B"
                input: ["text"]
                cost: {input: 0, output: 0, cacheRead: 0, cacheWrite: 0}
                contextWindow: 32768
                maxTokens: 32768
      agents:
        defaults:
          model:
            primary: "ollama/llama3.2:1b"
  storage:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openclaw
  networking:
    networkPolicy:
      enabled: false
    ingress:
      enabled: false
