apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: ai
spec:
  serviceAccountName: openclaw
  env:
    - name: GEMINI_API_KEY
      valueFrom:
        secretKeyRef:
          name: openclaw-llm-keys
          key: GEMINI_API_KEY
    - name: OPENROUTER_API_KEY
      valueFrom:
        secretKeyRef:
          name: openclaw-llm-keys
          key: OPENROUTER_API_KEY
    - name: GH_CONFIG_DIR
      value: /home/openclaw/.openclaw/.config/gh
    - name: PATH
      value: /home/openclaw/.openclaw/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  config:
    raw:
      gateway:
        controlUi:
          allowedOrigins:
            - "https://openclaw.wombat-wahoo.ts.net"
      agents:
        defaults:
          model:
            primary: "openrouter/deepseek/deepseek-chat"
  storage:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openclaw
  networking:
    networkPolicy:
      enabled: false
    ingress:
      enabled: false
