apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: ai
spec:
  env:
    - name: OLLAMA_HOST
      value: "http://ollama.ai.svc.cluster.local:11434"
  config:
    raw:
      agents:
        defaults:
          model:
            primary: "ollama/llama3.2:1b"
  storage:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: openclaw
  networking:
    networkPolicy:
      enabled: false
    ingress:
      enabled: true
      className: tailscale
      hosts:
        - host: openclaw
