apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: open-webui
  resources:
    requests:
      storage: 2Gi
