apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-storage
spec:
  storageClassName: frigate-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
spec:
  storageClassName: frigate-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
