apiVersion: ENC[AES256_GCM,data:t2c=,iv:aWCKpr5iNkQEMgvzvpWtbOlFh6yf3CES5AQMyJ/EmKs=,tag:uTiuy/6j7cvpQXzfgQdyYg==,type:str]
kind: ENC[AES256_GCM,data:j5u/HBDX,iv:LEylOqjMtvL4AEhxjuiz8NcNjK/0gaeYSo5Yg/IRxZI=,tag:3Z28BPZSY3VTahnQTaoEJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b18FIjc=,iv:q+BRDbEe/WwH6KcT+kJhscK3W1cInxVb/ZvDFx77Iu8=,tag:yrD3gHbJXlODTCJpMKsUcg==,type:str]
    namespace: ENC[AES256_GCM,data:RkCCWej0Hw==,iv:M7hNmX4UXIeqxk9v/tHYodTlfxKizNDNc7aWV1BOJLg=,tag:E69S/BFCP5N+bWDKvHk/hw==,type:str]
type: ENC[AES256_GCM,data:hT2W30oL,iv:NNhL36dsy2/vbp6LZU4kVnXS1v317x9IE7ur2IewQxI=,tag:HzOpxJ6DIMtH2bCvVeTPNw==,type:str]
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:IT77uqa6/Ttu0BQ=,iv:Vz4IqJ4FHgp126uSQv5esMSg9yGlkEmHlyUfgT25fmw=,tag:Vbg0JTF5CrPfa2ENBDHRTw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:qp3qb/BIoEFv0HcoJFwwyuZhMeAWn2vpj2Ghebh6,iv:16OJW/5HOedj5atvUh3sGofxQmpnROiGo6eH/uos5TU=,tag:gWbFx0JwCEzqAev2FhddOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaFFaaHJ0bGx6dHdPTFpN
            Uk41RnNDdFNORTJtQUZzL1ZJc1FERXJ2dGowCkY2ZkZpTVhRelNvMG1mYTIrWjRk
            UmlrWldIcnJQT1oxWloySmlmQ1RxWmMKLS0tIDBVU1hNK1p0OUdxMERVYmJEekl3
            Z1N5RW1IMlp4bmJCd2drMDM4L1ZmV1EKY+rOG4UDs000dCpe3gK249cdG93fDQAg
            coo7Xoxlh7aLIRewaP5SgWcTMlMfe65qKe4zEwB4AqOOgonVwCXyYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-07-18T09:10:24Z"
    mac: ENC[AES256_GCM,data:O8y6WrwnFCXzRCoDvnQtLb/gdZ4ulkJ9V/XhrA0uUrot0Rhc+PRTdHeH1DZ14dDRy0E97+jF37Ng/J4UP1f0yi1bl8O6MlFdFYC2BySz9wxHmfIopU+q9V/cE6Nvez5acR4jSEGl0rMJzik8yaz5Mj3byIj+svt/qQaAQ4b/4c0=,iv:IAbK/tY5Fw797mlUiV41ERTrOQ85UZhhnf7EqZc4NlI=,tag:xUlMNQM0/FBVuiRyBZKCiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
