apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: platform
spec:
  project: default
  source:
    repoURL: git@github.com:brendanPro/homelab.git
    targetRevision: main
    path: argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
