---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
- Home management:
    - Home assistant:
        href: "https://homeassistant.wombat-wahoo.ts.net"
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/home-assistant.svg
        description: Server de centralisation domotique
        namespace: smart-home
        app: homeassistant
        showStats: true
    - Vaultwarden:
        href: "https://newvaultwarden.wombat-wahoo.ts.net"
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/vaultwarden.svg
        description: Coffre fort de mot de passe
        namespace: vaultwarden
        app: vaultwarden
        showStats: true
    - Frigate:
        href: "https://frigate.wombat-wahoo.ts.net"
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/frigate.svg
        descritpion: Solution de nvr opensource
        namespace: smart-home
        app: frigate
        showStats: true
        widget:
            type: frigate
            url: http://frigate.smart-home:5000
            enableRecentEvents: true
    - Zigbee:
        href: "https://zigbee2mqtt.wombat-wahoo.ts.net"
        icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/zigbee2mqtt.svg
        descritpion: Zigbee2MQTT permet de connecter des appareils Zigbee pour les contrôler via homeassistant
        namespace: smart-home
        app: zigbee2mqtt
        showStats: true
