apiVersion: ENC[AES256_GCM,data:jYE=,iv:tZ4veHoXGRjK5Khc2nQyf/Ijd/vf+IN6FFR7Lj84rvI=,tag:MLbMhFy6Lk9G3vCWoSM1gg==,type:str]
kind: ENC[AES256_GCM,data:K0rkRRMC,iv:jjJHtZe0If2O6UCm0TnA5ZO3GFp5Nm3Wo3jWOpHpick=,tag:3nfUhKSjXhdguKo1AUDiZw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CqtAQAaeyfQczV6gzQ==,iv:t4IPdyj+KD9hZHilpFkl3Xze6le8bYq723Gwty06j04=,tag:U4GvXS9H9uZMJgT2J1Lh6g==,type:str]
    namespace: ENC[AES256_GCM,data:C76/y1C3Ig==,iv:uqtFeX50dURdYDEvFuF7S8787O4a1UKZzet8Bb13zWw=,tag:9SEToOi30IEF8gwwXOXprA==,type:str]
type: ENC[AES256_GCM,data:sSVE3A9y,iv:F4AsD/LwRouz4J0w19uo3+jD1jcO5N3vCYKkMXVQuYs=,tag:Q3euCZ8w6l4AUYs1RJWfFg==,type:str]
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:SVAgvn+VIDDi/VG3cBVI2t8YLnPB0n2wfa7sG2W+ARM=,iv:8eI0AgsUC/crYHY8p9QG/nSmc0mpxol9Nx6EtiHvmVY=,tag:Zm+eVcY1g79QmxsrIlkXmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuU3o3YXBWaGF3MVVvWko5
            S0ZCWGJNVVdPWWhnRlhzRGpsQllVNjQ5WnlBClJ5NnduajcwTTNudWFqZ2xvOXBi
            V1VhSlZ0SEU3NzI5NWhhREcxRW9qUTQKLS0tIHF1Rys1R1dxYjY2RGttY2xid1Nk
            Y0p3Y3ZHTDNFVzFsSSticG41ZDA0WW8KPBvy4A40W9/GOBZcMERqG5UH9bVRiMFQ
            8JAJG+8uJMb4qW78Ls8Ga6hOf9VGDqhuPI0Dj399jaxt31XUy2GWpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19cgxjr3phxdw5g8fg49weueyx2dvhn54qlkjesnhkr562axu6y5srah56v
    lastmodified: "2026-08-02T18:02:18Z"
    mac: ENC[AES256_GCM,data:wHTKMboQuv8YePptXdbALXDFRWjo77XMLCDEcGkYsMMSHfZeVh4TfY74wSkf1aohBDqe0Osw4uC0kNyWQeUtZ7DlbzNminJ2NqtYkWeAZfpVGud1A7FFsORuTv8MG5lOEc0ezP1U8ljeumxse3cPhhoQfQz3vYTEsE++pbOuIys=,iv:hGKuwXIF50X/UKn/aUhiZI+byBsCvXqey19Lr818y/g=,tag:9scf0KWuVgfusKXLYPliNw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
