apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: gitea-charts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    helm.sh/chart: memcached-4.2.20
  name: gitea-charts-memcached
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gitea-charts
      app.kubernetes.io/name: memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: gitea-charts
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: memcached
        helm.sh/chart: memcached-4.2.20
    spec:
      containers:
      - args:
        - /run.sh
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MEMCACHED_USERNAME
          value: ""
        - name: MEMCACHED_PASSWORD
          valueFrom:
            secretKeyRef:
              key: memcached-password
              name: gitea-charts-memcached
        image: docker.io/bitnami/memcached:1.6.6-debian-10-r54
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          tcpSocket:
            port: memcache
          timeoutSeconds: 5
        name: memcached
        ports:
        - containerPort: 11211
          name: memcache
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: memcache
          timeoutSeconds: 3
        resources:
          limits: {}
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: false
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - emptyDir: {}
        name: tmp