apiVersion: v1
kind: Service
metadata:
  name:  adguard
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http-initial
    nodePort: 30350
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
    nodePort: c
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
    nodePort: 30417
